# Homework 7


**Concepts covered:**

numpy arrays, array element access, basic descriptive statistics, initializing arrays, numpy functions and methods.  


**Instructions:**

Be sure to run each code block after you edit it to make sure it runs as expected. When you are done, we strongly recommend you run all the code from scratch (Runtime menu -> Restart and Run all) to make sure your current code works for all problems.

If your code raises an exception when run from scratch, it will interfere with the auto-grader process causing you to lose some or all points for this homework. Please ask for help on Piazza, attend office hours or schedule an appointment with your learning facilitator if you get stuck.


**Warning about AI:**

While we encourage you to use AI to generate practice problems, **we recommend against using generative AI in the strongest terms** to solve any part of this assignment. The goal of this assignment is for you to learn these concepts, and while using AI may help you obtain solutions to these problems, you will cheat yourself out of the learning that comes from working through the problems yourself.

**Sample Output:**

For each problem description, a sample output has been included to show what the expected output should be.


**Docstrings and Comments:**

Include a *documentation string* (docstring) for each function definition, as well as comments in the body of your code to explain each control structures (e.g., decision, loop), function call, or formula.

**Review Problem 1**

**Concept:** *List data type, list comprehension.*

**Task:**

Write a function `stdev(values)` that takes a 1D Python list of numbers and returns the population standard deviation.

**Sample Output:**


```
stdev([1, 2, 3]) should return approximately 0.8164965809

stdev([5, 5, 5, 5]) should return 0.0
```


In [1]:
def stdev(values):
  '''
  takes 1D Python list of numbers and returns the population standard deviation
  '''
  # gets the mean of the list
  mean = sum(values) / len(values)
  # get the variance
  variance = sum((x - mean) ** 2 for x in values) / len(values)
  # returns the variance
  return variance ** 0.5

In [2]:
# TO DO: WRITE YOUR TEST CASES HERE
# stdev([3, 5, 9])
print(f'std([1, 2, 3]) should return approximately {stdev([1, 2, 3])}')
print(f'stdev([5, 5, 5, 5]) should return {stdev([5, 5, 5, 5])}')

std([1, 2, 3]) should return approximately 0.816496580927726
stdev([5, 5, 5, 5]) should return 0.0


**Review Problem 2**

**Concept:** *List element access.*

**Task:**

Write a function `sum_list(a, b)` that takes two same-length 1D lists and returns a new list containing the element-wise sums.

If the lengths differ, print a message indicating incompatible lengths in this format: Incompatible lengths: {len(a)} vs {len(b)}.
Use list comprehension for this, not numpy.

**Sample Output:**

```
sum_list([2, 4, 6], [1, 3, 5]) → [3, 7, 11]
```


In [3]:
def sum_list(a, b):
  '''
  takes two same-length 1D lists and returns a new list containing the element-wise sums
  '''
  # if the length of list a is not equal to list b
  if len(a) != len(b):
    # print the following 
    print(f'Incompatible lengths: {len(a)} vs {len(b)}')
  # if the length is equal to b
  else:
    # return the sum of the index of both lists for the range of the length of a
    return [a[i] + b[i] for i in range(len(a))]

Test cases for problem 2

In [4]:
# TO DO: WRITE YOUR TEST CASES HERE
print(f'sum_list([2, 4, 6], [1, 3, 5]) -> {sum_list([2, 4, 6], [1, 3, 5])}')


sum_list([2, 4, 6], [1, 3, 5]) -> [3, 7, 11]


The following starter code will be used in several problems. Run the following cell before continuing.

In [5]:
# STARTER CODE TO DEFINE SOME NUMPY ARRAYS:
import numpy as np

a = np.arange(12)
b = np.array([i * 2 for i in range(1,13)])
c = np.random.randint(0, 10, 12)
print(f'a = {a}')
print(f'b = {b}')
print(f'c = {c}')



a = [ 0  1  2  3  4  5  6  7  8  9 10 11]
b = [ 2  4  6  8 10 12 14 16 18 20 22 24]
c = [2 8 3 8 4 2 3 2 4 5 1 7]


**Problem 3**

**Concept:** *Array operations.*

**Task:**

Using the arrays a, b, c defined in the starter code:

a.   Compute sum of arrays `a` plus `b`, and store the result in the variable `x`.

b.   Compute the product of arrays `a` and `b`, and store the result in the variable `y`.

c.   Compute the dot product of arrays `a` and `b`, and store the result in the variable `z`.

d.   Re-shape the array `x` as a 2x6 array, and store the result in the variable `q`.

e.   Re-shape the array `y` as a 6x2 array, and store the result in the variable `r`.

f.   Compute the dot product of arrays `q` and `r`, and store the result in the varaible `s`.

Print `x`, `y`, `z`, `q`, `r`, `s` as you go to check your work.

**Sample Output:**

```
x = [ 3  7 11 15 19 23 27 31 35 39 43 47]
y = [  0   6  18  36  60  90 126 168 216 270 330 396]
z = 2184

q =
[[ 3  7 11 15 19 23]
 [27 31 35 39 43 47]]

r =
[[  0   6]
 [ 18  36]
 [ 60  90]
 [126 168]
 [216 270]
 [330 396]]

s =
[[15660 20484]
 [37476 49020]]

```


In [6]:
# TO DO: WRITE YOUR SOLUTION HERE
''' array operations'''
x = a + b
y = a * b
q = x.reshape(2, 6)
r = y.reshape(6, 2)

print(f'x = {a + b}')
print(f'y = {a * b}')
print(f'z = {np.dot(a, b)}')
print(f'q = {x.reshape(2, 6)}')
print(f'r = {y.reshape(6, 2)}')
print(f's = {np.dot(q, r)}')

x = [ 2  5  8 11 14 17 20 23 26 29 32 35]
y = [  0   4  12  24  40  60  84 112 144 180 220 264]
z = 1144
q = [[ 2  5  8 11 14 17]
 [20 23 26 29 32 35]]
r = [[  0   4]
 [ 12  24]
 [ 40  60]
 [ 84 112]
 [144 180]
 [220 264]]
s = [[ 7060  8848]
 [16060 20440]]


**Problem 4**

**Concept:** *Array operations, iteration with loop, numpy functions and methods.*

**Task:**

Write a function `mean_rowwise(x)` that takes a 2D numpy array and returns a 2D column vector containing the mean of each row.

**Numeric Example:**

If `x = [[1,2,3],[10,0,-10]]`, the row means are `[[2.],[0.]]`.


**Example Function Call:**

```
mean_rowwise(np.array([[0.2, 0.3, 0.4]])) returns [[0.3]]
```




In [7]:
# TO DO: WRITE YOUR SOLUTION HERE
def mean_rowwise(x):
  '''
  takes a 2D numpy array and returns a 2D column vector containing the mean of each row
  '''
  # makes x an array
  x = np.array(x)
  # finds mean of each row, returns as vector
  return np.mean(x, axis=1).reshape(-1, 1)


Test cases for problem 4

In [8]:
# TO DO: WRITE YOUR TEST CASES HERE
mean_rowwise([[1, 2, 3], [10, 0, -10]])
print(f'mean_rowwise(np.array([[0.2, 0.3, 0.4]])) returns {mean_rowwise(np.array([[0.2, 0.3, 0.4]]))}')


mean_rowwise(np.array([[0.2, 0.3, 0.4]])) returns [[0.3]]


**Problem 5**

**Concept:** *Array operations, iteration with loop, boolean values, numpy functions and methods.*

**Task:**

Write a function `check_row_sum(x)` that returns `True` if every row in a 2D numpy array sums to 1.0 (tolerance: between `0.999` and `1.001`), otherwise return `False`.

**Example Function Calls:**

`check_row_sum([[0.2,0.8],[0.5,0.5]])` returns `True`

`check_row_sum([[0.0, 1.0], [0.9999, 0.0012]])` returns `False`
```



In [9]:
# TO DO: WRITE YOUR SOLUTION HERE
def check_row_sum(x):
  '''
  returns True if every row in a 2D numpy array sums to 1.0
  '''
  # calculate the sum of each row
  row_sums = np.sum(x, axis=1)
  # returns True if all of the row sums are close to 1. if not it will return False
  return np.all((row_sums >= 0.999) & (row_sums <= 1.001))


Test cases for problem 5

In [10]:
# TO DO: WRITE YOUR TEST CASES HERE
print(f'check_row_sum([0.2,0.8], [0.5,0.5]]) returns {check_row_sum([[0.2,0.8], [0.5,0.5]])}')
print(f'check_row_sum([0.0,1.0], [0.9999,0.0012]]) returns {check_row_sum([[0.0,1.0], [0.9999,0.0012]])}')



check_row_sum([0.2,0.8], [0.5,0.5]]) returns True
check_row_sum([0.0,1.0], [0.9999,0.0012]]) returns False


**Problem 6**

**Concept:** *Array operations, numpy functions and methods.*

**Task:**

Write a function `softmax(z)` that takes in a 1D numpy array of values $z_i$, and returns an array composed of $\frac{e^{z_i}}{\sum e^{z_i}}$.

The output array shape should be the same as the input array shape.

This formula is the [softmax](https://en.wikipedia.org/wiki/Softmax_function) formula used to adjust raw machine learning outputs into more suitable probability estimates.

**Example Function Calls:**

`softmax(np.array([0,0]))` returns `np.array([0.5, 0.5])`

`softmax(np.array([-1, 0, 1]))` returns `np.array([0.09003057 0.24472847 0.66524096])`


In [11]:
# TO DO: WRITE YOUR SOLUTION HERE
def softmax(z):
  ''' 
  takes in a 1D numpy array of values z and returns an array'''
  # e^x to each of the values in the array
  z = np.exp(z)
  # divides each of the exponential values by sum to get the softmax prob, the values equal to 1
  return z / np.sum(z)


Test cases for problem 6

In [24]:
# TO DO: WRITE YOUR TEST CASES HERE
print(softmax(([0,0])))
softmax([-1, 0, 1])



[0.5 0.5]


array([0.09003057, 0.24472847, 0.66524096])

**Problem 7**

**Concept:** *Array operations.*

**Task:**
Write `softmax_2d(z)` that applies softmax row-by-row to a 2D numpy array, returning an array of the same shape.

**Example Function Calls:**

`softmax_2d(np.array([[0,0],[1,1]]))` returns `np.array([[0.5,0.5],[0.5,0.5]])`


In [13]:
# TO DO: WRITE YOUR SOLUTION HERE
def softmax_2d(z):
  ''' 
  applies softmax row-by-row to a 2D numpy array, returning an array of the same shape'''
   # e^x to each of the values in the array
  z = np.exp(z)
  # divides each row by its row sum to become softmax prob.
  return z / np.sum(z, axis=1, keepdims=True)


Test cases for problem 7

In [14]:
# TO DO: WRITE YOUR TEST CASES HERE
softmax_2d(([[0,0],[1,1]]))


array([[0.5, 0.5],
       [0.5, 0.5]])

**Problem 8**

**Concept:** *Descriptive statistics, row-wise operations, numpy functions and methods.*

**Task:**

Write `three_stats(x)` that takes an `n x k` array and returns an 3 by N array of:

1. row minimums

2. row medians

3. row maximums


**Hint:**
You can use np.min, np.median, np.max

**Example Function Calls:**

`three_stats(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]]))`
returns
`np.array([[1. 4. 7.], [2. 5. 8.], [3. 6. 9.]])`



In [ ]:
# TO DO: WRITE YOUR SOLUTION HERE
def three_stats(x):
  '''
  takes an n x k array and returns a 3 by N array of min, meds, max'''
  # find min value in each row
  minimum_row = np.min(x, axis=1)
   # find median value in each row
  median_row = np.median(x, axis=1)
   # find max value in each row
  max_row = np.max(x, axis=1)
  # returns the min, med, and max rows
  return np.vstack([minimum_row, median_row, max_row])


Test cases for problem 8

In [25]:
# TO DO: WRITE YOUR TEST CASES HERE
three_stats(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]))

array([[1., 4., 7.],
       [2., 5., 8.],
       [3., 6., 9.]])

**Problem 9**

**Concept:** *Row-wise operations, numpy functions and methods.*

**Task:**
Write `max_row_sum(a)` that takes a 2D numpy array and returns the largest row sum.

**Numeric Example:**

```[[1,2],[10,-1],[0,0]] row sums [3,9,0] → returns 9```

**Example Function Call:**

`max_row_sum(np.array([[1, 2, 3], [9, 9, 9], [1000, 100, 900]]))` returns `2000`




In [ ]:
# TO DO: WRITE YOUR SOLUTION HERE
def max_row_sums(a):
  ''' 
  takes a 2D numpy array and returns the largest row sum'''
  # return the row sum and return largest one
  return np.max(np.sum(a, axis=1))


Test cases for problem 9

In [27]:
# TO DO: WRITE YOUR TEST CASES HERE
max_row_sums(np.array([[1, 2, 3], [9, 9, 9], [1000, 100, 900]]))

np.int64(2000)

**Problem 10**

**Concept:** *Array operations; thinking about dimensions and element access.*

**Task:**

Write the function `array_init_parameters(a)` that returns either:

*  if all elements are the same and the array `a` can be recreated using `np.full((w, h), v)`, return the tuple `(w, h, v)` corresponding to (width, height, value)

* otherwise return `None`

**Numeric Example:**

```[[7,7],[7,7]] → (2,2,7)```

```[[7,7],[7,8]] → None```



In [ ]:
# TO DO: WRITE YOUR SOLUTION HERE
def array_init_parameters(a):
  ''' 
  returns tuple corresponding to width, height value or returns None'''
  # check if every value in array is the same as the first value
  if np.all(a == a[0, 0]):
    # gets number of rows and columns
    w, h = a.shape
    # stores repeated value in the array
    v = a[0, 0]
    # return array and tuple
    return (w, h, v)
  # returns None if array wasn't created from one repeat value
  return None


Test cases for problem 10

In [37]:
# TEST CASES TO TRY:

# array_init_parameters(np.array([[0]]))

# array_init_parameters(np.array([[0, 1]]))

# array_init_parameters(np.array([[3], [3]]))

print(f'[[7,7],[7,7]] -> {array_init_parameters(np.array(([[7,7],[7,7]])))}')


[[7,7],[7,7]] -> (2, 2, np.int64(7))


**Problem 11**

**Concept:** *Array operations; thinking about dimensions and element access.*

**Task:**

[Kakuro](https://en.wikipedia.org/wiki/Kakuro) is a logic puzzle where the goal is to fill in numbers so that the rows and columns add up to specified numbers.

Write `kakuro_test(a, row_sums, column_sums)` that returns `True` if:

* each row sum matches `row_sums`

* each column sum matches `column_sums`

* Otherwise return `False`.

**Numeric Example:**

For the input
`kakuro_test(np.array([[7, 2], [3, 4]]), [9, 7], [10, 6])`

The row sums are 7+2=9 and 3+4=7, which matches the third element `[9, 7]`

The column sums are 7+3=10 and 2+4=6, which matches the fourth element `[10, 6]`

So this should return `True`



In [46]:
# TO DO: WRITE YOUR SOLUTION HERE
def kakuro_test(a, row_sums, column_sums):
  ''' 
  returns True of each row sum matches row sums, column sums, otherwise return False
  '''
  # return 


Test cases for problem 11

In [47]:
# TEST CASES TO TRYU

# this should return True
# p11_test_1_result = kakuro_test(np.array([[0, 1, 2], [3, 4, 5]]), [3, 12], [3, 5, 7])
# print(f'p11_test_1_result = {p11_test_1_result}')

# this should return False
p11_test_2_result = kakuro_test(np.array([[7, 2], [3, 4]]), [9, 7], [10, 6])
print(f'p11_test_2_result = {p11_test_2_result}')



p11_test_2_result = None


**Problem 12**

**Concept:** *File reading, parsing data values, array creation.*

**Task:**
Write the function `read_csv_to_array(filename)` that reads a CSV file, discards the header row, converts each element to a floating-point number, and returns a 2D numpy array.

**Sample Output:**

If file contains:

```
foo,bar
2,4
6,8
```

The function should return:
```
np.array([[2. 4.][6. 8.]])
```

In [52]:
# TO DO: WRITE YOUR SOLUTION HERE
def read_csv_to_array(filename):
  ''' 
  reads CSV, discards head row, converts each elemnt to floating-point number and returns 2D numpy array
  '''
  with open(filename, 'r') as file:
    lines = file.readlines()

    data = []
    for line in lines[1:]:
      line = line.strip()
      if line:
        row = [float(x) for x in line.split(',')]
        data.append(row)

    return np.array(data)

Test cases for problem 12

In [53]:
# TEST CASES HERE
data = read_csv_to_array("data1.csv")
print(data)


[[ 22. 183.  51.]
 [ 62. 168.  57.]
 [ 42. 150.  98.]
 [ 49. 163.  90.]
 [ 49. 129.  98.]
 [ 60. 171.  90.]
 [ 59. 181.  65.]
 [ 62. 136.  83.]
 [ 18. 144.  67.]
 [ 64. 189.  73.]]


**Problem 13**

**Concept:** *File reading, parsing data values, array creation.*


**Task:**

Write the function `get_column_stats(filename)` that a CSV file, discards the header row, and returns a 2D numpy array where the rows contain in order: the means, standard deviations, minimums, and maximums, of each column.

**Sample Output:**

If file contains:
```
a,b,c
1,2,3
4,5,6
```
The resulting columns means are

```np.array([[2.5, 3.5, 4.5], [1.5, 1.5, 1.5], [1, 2, 3], [4, 5, 6]])```


In [54]:
# TO DO: WRITE YOUR SOLUTION HERE
def get_column_stats(filename):
  ''' 
  discards header row, returns 2D numpy array where the rows contain in order - means, standard deviations, min, max of each column
  '''
  data = read_csv_to_array(filename)
  means = np.mean(data, axis=0)
  std_devs = np.std(data, axis=0)
  minimums = np.min(data, axis=0)
  maximums = np.max(data, axis=0)
  return np.vstack([means, std_devs, minimums, maximums])


Test cases for problem 13

In [55]:
# TEST CASES HERE
stats = get_column_stats("data1.csv")
print(stats)


[[ 48.7        161.4         77.2       ]
 [ 15.88112087  19.6936538   16.09844713]
 [ 18.         129.          51.        ]
 [ 64.         189.          98.        ]]
